lib/components/ms-action-bar/MsActionBar.vue
lib/components/ms-sorter/MsSorter.vue

Before you submit this pull request, please make sure to:
closes Scille/megashark-lib#15 
closes Scille/megashark-lib#16

[MS] Update action-bar style

---

lib/components/ms-input/MsInput.vue
lib/components/ms-input/MsPasswordInput.vue
lib/components/ms-stepper/MsWizardStepper.vue
lib/theme/variables/fonts.scss

Update fonts according to the visual identity
closes #14

[MS] Update fonts variables

---

lib/components/ms-action-bar/MsActionBarButton.vue

[MS] Add MsImage on actionbar button

---

README.md

Update the Readme for the lib-megashark

---

lib/components/ms-spinner/MsSpinner.vue

I updated the spinner with svg content.
closes #52
closes #46

[MS] Change custom spinner

---

lib/theme/variables/colors.scss
lib/theme/variables/fonts.scss
lib/theme/variables/shadows.scss

[MS] Add megashark style for parsec-sign

---

lib/common/validation.ts
tests/unit/specs/testPasswordValidation.spec.ts
vite.config.ts

[MS] add validation functions

---

lib/components/ms-dropdown/MsDropdown.vue
lib/components/ms-input/MsInput.vue
lib/components/ms-input/MsPasswordInput.vue
lib/components/ms-input/MsSearchInput.vue
lib/components/ms-text/MsReportText.vue
lib/theme/components/inputs.scss
lib/theme/variables/colors.scss
src/views/HomePage.vue

[MS] Fix visual bugs

---

lib/components/ms-modal/types.ts
lib/components/ms-modal/utils.ts
lib/components/ms-toggle/MsBooleanToogle.vue
lib/components/ms-toggle/index.ts
lib/components/ms-types.ts
lib/locales/en-US.json
lib/locales/fr-FR.json
src/views/HomePage.vue

[MS] Add `MsBooleanToggle` component

---

lib/components/ms-input/MsCodeValidationInput.vue
lib/components/ms-input/index.ts
lib/locales/en-US.json
lib/locales/fr-FR.json
src/locales/en-US.json
src/locales/fr-FR.json
src/views/HomePage.vue

[MS] Add `CodeValidation` in lib

---

lib/components/ms-stripe/MsStripeCardElement.vue
lib/components/ms-stripe/MsStripeCardForm.vue

- update MsStripeCardForm to put Expiry and Cvc on same line
- update icons from outline to filled
- add focus border halo effect
closes #92

feat: Improve MsStripeCard components style

---

lib/components/ms-dropdown/MsDropdown.vue

Add alignment prop to ms-dropdown

---

lib/components/ms-card/MsSummaryCard.vue
lib/components/ms-card/MsSummaryCardItem.vue

[MS] Fix text length for row items

---

lib/theme/components/inputs.scss

[MS] Hide password toggle visibility on Edge

---

lib/components/ms-dropdown/MsAddressDropdown.vue
lib/components/ms-input/MsAddressInput.vue
src/views/HomePage.vue

related to https://github.com/Scille/parsec-sign/issues/136

[MS] Updated address dropdown

---

lib/assets/images/import-multiple-files.svg
lib/components/ms-image/images.ts

[MS] Added image `import multiple files`

---

lib/components/ms-progress/MsProgress.vue

[MS] Added class progress bar variation

---

lib/components/ms-action-bar/MsActionBar.vue
lib/theme/components/modals.scss
lib/theme/variables/colors.scss
lib/theme/variables/fonts.scss
src/views/HomePage.vue

Update fill-available to fix cross browser compatibility

---

lib/components/ms-input/MsChoosePasswordInput.vue
lib/locales/en-US.json
lib/locales/fr-FR.json
tests/components/specs/testMsChoosePasswordInput.spec.ts

Closes https://github.com/Scille/parsec-cloud/issues/8133

Change criteria in MsChoosePasswordInput

---

lib/components/ms-action-bar/MsActionBar.vue
lib/theme/components/action-bar.scss
lib/theme/global.scss

linked to https://github.com/Scille/parsec-cloud/issues/9141

[MS] Replaced `contextual-menu` to `action-bar`

---

lib/services/stripe.ts

Closes https://github.com/Scille/parsec-sign/issues/194

Add placeholder font color in stripe element

---

lib/components/index.ts
lib/components/ms-draggable/MsDraggable.vue
lib/components/ms-draggable/index.ts
src/locales/en-US.json
src/locales/fr-FR.json
src/views/HomePage.vue

related to: https://github.com/Scille/parsec-cloud/issues/9632

Implements MsDraggable

---

lib/theme/components/toasts.scss

closes https://github.com/Scille/parsec-sign/issues/212

[MS] Fixed white screen toast

---

lib/components/ms-dropdown/MsSmallDisplayDropdown.vue
lib/components/ms-dropdown/index.ts
lib/components/ms-dropdown/utils.ts
lib/theme/components/_modals.scss
src/locales/en-US.json
src/locales/fr-FR.json
src/views/ComponentsPage.vue

Closes https://github.com/Scille/parsec-cloud/issues/9516

MsSmallDisplayDropdown

---

lib/components/ms-dropdown/MsSmallDisplayDropdown.vue
lib/components/ms-input/MsChoosePasswordInput.vue
lib/components/ms-input/MsSearchInput.vue
lib/components/ms-modal/MsModal.vue
lib/components/ms-modal/MsSmallDisplayStepperModal.vue
lib/components/ms-textarea/MsTextarea.vue
lib/theme/components/_inputs.scss
lib/theme/components/_modals.scss
src/locales/en-US.json
src/locales/fr-FR.json
src/views/ComponentsPage.vue
src/views/HomePage.vue
src/views/example-block/ExampleBlockLine.vue

- Removed useless code `closeBtn-container` on modal
- Edited lib for futur responsive (everything is `width: 100%`)

[MS] Updated small changes on lib

---

lib/components/ms-modal/MsModal.vue
lib/components/ms-modal/MsSmallDisplayStepperModal.vue
lib/theme/components/_modals.scss

Fix:
- Bug closeBtn in Safari is shrinked (height)
- Uniformed modal padding

Update modal minor visual issues

---

lib/components/ms-card/MsSummaryCard.vue
lib/components/ms-input/MsCodeValidationInput.vue

[MS] Responsive summary card

---

lib/components/ms-action-bar/MsActionBar.vue
lib/components/ms-action-bar/MsActionBarButton.vue
lib/components/ms-datetime-picker/MsDatetimePicker.vue
lib/components/ms-dropdown/MsDropdown.vue
lib/components/ms-input/MsCodeValidationInput.vue
lib/components/ms-modal/MsModal.vue
lib/components/ms-sorter/MsSorter.vue
lib/components/ms-stepper/MsWizardStepper.vue
lib/components/ms-stepper/MsWizardStepperStep.vue
lib/components/ms-text/MsReportText.vue
lib/theme/components/_inputs.scss
lib/theme/global.scss
src/views/ComponentsPage.vue

[MS] Restyle components

---

lib/components/ms-modal/MsAlertModal.vue
lib/components/ms-modal/MsModal.vue
lib/theme/components/_modals.scss
src/views/ComponentsPage.vue

Insert the report text as content in MsModal instead of a subtitle (in the header).

[MS] Update alert modal style

---

lib/components/ms-dropdown/MsDropdownPopover.vue
lib/components/ms-input/MsInput.vue
lib/components/ms-input/MsPasswordInput.vue
lib/components/ms-input/MsSearchInput.vue
lib/components/ms-modal/MsModal.vue
lib/components/ms-stripe/MsStripeCardElement.vue
lib/components/ms-stripe/MsStripeCardForm.vue
lib/components/ms-textarea/MsTextarea.vue
lib/services/stripe.ts
lib/theme/components/_inputs.scss
lib/theme/variables/_fonts.scss
lib/theme/variables/_shadows.scss

https://github.com/user-attachments/assets/fd9fbeb9-8669-4882-80ad-bf390c619f77

[MS] Added click on input label to focus

---

lib/components/ms-card/MsSummaryCard.vue
lib/components/ms-stripe/MsStripeCardDetails.vue
lib/components/ms-stripe/MsStripeCardElement.vue

- StripeCard can be set to 2 different sizes: `large` or `small`
- SummaryCard (add subtitle and remove some style to be customize more easily)

[MS] Responsive components improvements
